### PR TITLE
Search users

### LINKED ISSUE #71: Users can search for other users through a search bar
Users can view other users’ profile pages (no private profiles bc we need more content)

Searching might be tricky and slow, instead we could use QR Code, or Clash of Clans style gamer tag for each profile?

Best idea so far:
- Have a map in DB of UserName/DisplayName → UserID
- Make one DB call of this map, and do all searching with the keys we have from this

### Tasks for this requirement:
- [ ] (devs fill in here with a link to your issues)
- [ ] 2
- [ ] 3

### LINKED ISSUE #159: Viewing archived route in RouteView screen crashes app
Passing the id of an archived route to the route view screen causes the app to crash. Expo immediately closes for me so I cant read the errors, this is the only error I could see while screen recording. I tried with all three archived routes, same error.

### PR DESCRIPTION
**Pull request by abrugal**
# Changes
Display searched users and archived routes in search screen. 

Note: Pressing the archived route takes you to the RouteView screen but crashes the app. An issue has been made for this #159. Also currently there are duplicate users that appear in the search results due to the cache having duplicates.

New Note: #159 has been fixed.

https://user-images.githubusercontent.com/5271307/217113785-c75a78df-47ee-4d2b-bb21-d73fb0e5348b.mp4

# Issue ticket number and link
Closes #71
Closes #159

### CODE REVIEW

File: screens/search/Search.tsx [hunk 1]
```diff
@@ -0,0 +1,113 @@
...
+  const [archivedRoutesSearchResults, setArchivedRoutesSearchResults] =
+    useState<String[]>([]);
+  const [tabViewed, setTabViewed] = useState<SearchTab>('users');
+
+  const baseBgColor = useColorModeValue('lightMode.base', 'darkMode.base');
+
+  const { isLoading, isError, data, error } = useSearchSubstringMatchers();
+
+  useEffect(() => {
+    if (!data) return;
```
Comment (tylerhm) [inline screens/search/Search.tsx:35]: Lets do explicit `undefined` check here. Data could theoretically be `false`.
```suggestion
    if (data === undefined) return;
```

File: screens/search/Search.tsx [hunk 2]
```diff
@@ -0,0 +1,113 @@
...
+            }}
+          />
+          <HStack w="full" justifyContent="space-around" p="3" space="md">
+            <Button
+              onPress={() => setTabViewed('routes')}
+              variant={tabViewed === 'routes' ? 'solid' : 'outline'}
+              rounded="full"
+              w="1/2"
+            >
+              Routes
```
Comment (tylerhm) [inline screens/search/Search.tsx:77]: Can we let the user know that these are only archived routes somehow? I feel like "routes" might be misleading.

**Review by tylerhm — APPROVED** [review]
This is so sick, nice job! Two comments, but approving to unblock.

File: screens/search/Search.tsx (hunk 2 above)
Comment (abrugal) [reply screens/search/Search.tsx:77]: Yeah, I was thinking of adding an extra option to filter between archived and active routes. I'll add that

Comment (tylerhm) [reply screens/search/Search.tsx:77]: Nice!

Comment (abrugal) [reply screens/search/Search.tsx]: For now I just made an extra button to choose between active and archived cause I couldn't think of a good design for filters. In the future we should change it into filters though, since we'll want to let the user filter for specific stuff on a route, like difficulty, etc.

Comment (tylerhm) [reply screens/search/Search.tsx]: Awesome, and agreed! This seems solid for now.
